spring.application.name=gestion-horas-api
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_horas
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true